db.genre.insert({ _id: 'AA', Name: 'Action / Adventure' });
db.genre.insert({ _id: 'AD', Name: 'Adult' });
db.genre.insert({ _id: 'AN', Name: 'Anthology' });
db.genre.insert({ _id: 'AP', Name: 'Anthropomorphics' });
db.genre.insert({ _id: 'AS', Name: 'Art Supplies' });
db.genre.insert({ _id: 'CJ', Name: 'Comics Journalism' });
db.genre.insert({ _id: 'CR', Name: 'Crime' });
db.genre.insert({ _id: 'DR', Name: 'Drama' });
db.genre.insert({ _id: 'DT', Name: 'Designer Toys' });
db.genre.insert({ _id: 'FA', Name: 'Fantasy' });
db.genre.insert({ _id: 'GA', Name: 'Gaming / Role Playing' });
db.genre.insert({ _id: 'HA', Name: 'Halloween' });
db.genre.insert({ _id: 'HO', Name: 'Horror' });
db.genre.insert({ _id: 'HS', Name: 'Historical' });
db.genre.insert({ _id: 'HT', Name: 'How to Draw' });
db.genre.insert({ _id: 'HU', Name: 'Humor/Comedy' });
db.genre.insert({ _id: 'KI', Name: 'Kids' });
db.genre.insert({ _id: 'LG', Name: 'Legend' });
db.genre.insert({ _id: 'LT', Name: 'Literary' });
db.genre.insert({ _id: 'MA', Name: 'Manga' });
db.genre.insert({ _id: 'MS', Name: 'Mystery' });
db.genre.insert({ _id: 'MU', Name: 'Music' });
db.genre.insert({ _id: 'MV', Name: 'Movie/TV' });
db.genre.insert({ _id: 'PC', Name: 'Pop Culture' });
db.genre.insert({ _id: 'PK', Name: 'Pokémon' });
db.genre.insert({ _id: 'RB', Name: 'Reality-Based' });
db.genre.insert({ _id: 'RF', Name: 'Reference/Art Books/How To' });
db.genre.insert({ _id: 'RL', Name: 'Religious' });
db.genre.insert({ _id: 'RO', Name: 'Romance' });
db.genre.insert({ _id: 'SF', Name: 'Science Fiction' });
db.genre.insert({ _id: 'SH', Name: 'Super-Hero' });
db.genre.insert({ _id: 'SN', Name: 'Seasonal' });
db.genre.insert({ _id: 'SP', Name: 'Sports' });
db.genre.insert({ _id: 'SU', Name: 'Surreal/Non-Linear' });
db.genre.insert({ _id: 'TY', Name: 'Toy' });
db.genre.insert({ _id: 'WR', Name: 'War' });
db.genre.insert({ _id: 'WS', Name: 'Western' });
db.genre.insert({ _id: 'XX', Name: 'Not Specieid' });
db.genre.insert({ _id: 'YA', Name: 'Yaoi' });